### PR TITLE
docs: Update README

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Adjust language from past tense in several sentences.

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits (n/a)
- [x] includes documentation (n/a)
- [x] adds unit tests (n/a)

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
NOTE: update the VAP sentence to something "ensure VAP is enabled".

**Review by aramase — COMMENTED** [review]
@benjaminapetersen could you sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)?

**Comment by benjaminapetersen** [comment]
@aramase CLA done 👍

**Pull request merged**
