### PR TITLE
chore: Use `Capabilities.KubeVersion` in helm charts

### LINKED ISSUE #61: Use `Capabilities.KubeVersion` in helm charts to determine the API version
Delete `kubernetesReleaseVersion` helm value and instead use `Capabilities.KubeVersion` to determine the correct api version.

for reference: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/templates/_helpers.tpl#L46-L55

### PR DESCRIPTION
**Pull request by omerap12**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Use Capabilities.KubeVersion instead of kubernetesReleaseVersion value
**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #61 

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Comment by aramase** [comment]
/retitle chore: Use `Capabilities.KubeVersion` in helm charts

**Review by aramase — CHANGES_REQUESTED** [review]
Please update the yamls in the [manifest_staging/charts](https://github.com/kubernetes-sigs/secrets-store-sync-controller/tree/main/manifest_staging/charts/) folder and revert any changes in `charts/`. 

`manifest_staging` folder is where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder with the next release.

**Comment by omerap12** [comment]
> Please update the yamls in the [manifest_staging/charts](https://github.com/kubernetes-sigs/secrets-store-sync-controller/tree/main/manifest_staging/charts/) folder and revert any changes in `charts/`.
> 
> `manifest_staging` folder is where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder with the next release.

Done

**Comment by aramase** [comment]
Found https://github.com/kubernetes-sigs/secrets-store-sync-controller/issues/78 as part of testing this.

**Comment by AlexanderStocks** [comment]
This is failing because we are relying solely on the Kubernetes version to determine the availability of the VAP resources in the tests and not altering the cluster config, which isn't always true because feature gates might not be enabled. Should we document this somewhere that if installing with a version before 1.30.0 (when VAPs were classed as stable) a user may need to alter their cluster config? @nilekhc

**Comment by nilekhc** [comment]
> This is failing because we are relying solely on the Kubernetes version to determine the availability of the VAP resources in the tests and not altering the cluster config, which isn't always true because feature gates might not be enabled. To fix this we will need to vary the cluster config provided for each test. Should we document somewhere that if installing with a version before 1.30.0 (when VAPs were classed as stable) a user may need to alter their cluster config? @nilekhc

@omerap12, we need to modify local-setup such that it takes correct feature gate in kind-config.yaml while creating cluster.

**Comment by omerap12** [comment]
> > This is failing because we are relying solely on the Kubernetes version to determine the availability of the VAP resources in the tests and not altering the cluster config, which isn't always true because feature gates might not be enabled. To fix this we will need to vary the cluster config provided for each test. Should we document somewhere that if installing with a version before 1.30.0 (when VAPs were classed as stable) a user may need to alter their cluster config? @nilekhc
> 
> @omerap12, we need to modify local-setup such that it takes correct feature gate in kind-config.yaml while creating cluster.

Ill take a look into it

**Comment by benjaminapetersen** [comment]
#89 will replace this one, we can close this.

**Comment by AlexanderStocks** [comment]
#89 includes these changes and fixes the issue with deploying on clusters with k8s versions <1.30

**Comment by enj** [comment]
/close

(per above discussion)

**Pull request closed without merging**
